package com.informaticsmatrix.birthdayapp.greenDao;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

import java.util.Date;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BIRTHDAY".
 */
@Entity
public class Birthday implements Parcelable{

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String age;
    private String dobString;
    private String message;
    private String phone;
    private java.util.Date dobDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Birthday() {
    }

    public Birthday(Long id) {
        this.id = id;
    }

    @Generated
    public Birthday(Long id, String name, String age, String dobString, String message, String phone, java.util.Date dobDate) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.dobString = dobString;
        this.message = message;
        this.phone = phone;
        this.dobDate = dobDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getDobString() {
        return dobString;
    }

    public void setDobString(String dobString) {
        this.dobString = dobString;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public java.util.Date getDobDate() {
        return dobDate;
    }

    public void setDobDate(java.util.Date dobDate) {
        this.dobDate = dobDate;
    }
    protected Birthday(Parcel in) {

        name = in.readString();
        age = in.readString();
        dobString = in.readString();
        message = in.readString();
        phone = in.readString();
        long tmpDobDate = in.readLong();
        dobDate = tmpDobDate != -1 ? new Date(tmpDobDate) : null;
        id = in.readLong();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(name);
        dest.writeString(age);
        dest.writeString(dobString);
        dest.writeString(message);
        dest.writeString(phone);
        dest.writeLong(dobDate != null ? dobDate.getTime() : -1L);
        dest.writeLong(id);
    }

    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Birthday> CREATOR = new Parcelable.Creator<Birthday>() {
        @Override
        public Birthday createFromParcel(Parcel in) {
            return new Birthday(in);
        }

        @Override
        public Birthday[] newArray(int size) {
            return new Birthday[size];
        }
    };

}
